name: Random Time Random Commits

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Random commits
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          COUNT=$(( (RANDOM % 7) + 1 ))

          for i in $(seq 1 $COUNT)
          do
            DELAY=$(( RANDOM % 1800 ))
            sleep $DELAY
            git commit --allow-empty -m "auto commit $i"
          done

          git push
